# Generated by Django 2.1.5 on 2019-01-09 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=300, null=True, unique=True)),
                ('discord_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('subscription_date_expire', models.DateTimeField(blank=True, null=True)),
                ('notify_7', models.BooleanField(default=False)),
                ('notify_3', models.BooleanField(default=False)),
                ('notify_24h', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
