# Generated by Django 2.1.5 on 2019-01-09 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announceusio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='created_at',
            new_name='created_on',
        ),
    ]
