# Generated by Django 2.1.5 on 2019-01-09 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announceusio', '0002_auto_20190109_0340'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='discord_username',
            field=models.CharField(blank=True, max_length=300, null=True, unique=True),
        ),
    ]
