# Generated by Django 2.1.5 on 2019-01-11 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announceusio', '0003_member_discord_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_activated',
            field=models.BooleanField(default=False),
        ),
    ]
