# Generated by Django 2.1.5 on 2019-01-11 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announceusio', '0004_member_is_activated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='discord_id',
            field=models.CharField(blank=True, max_length=300, null=True, unique=True),
        ),
    ]
