# Generated by Django 2.1.5 on 2019-01-11 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announceusio', '0006_invite'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=25)),
                ('item_name', models.CharField(default='announceus.io - PREMIUM', max_length=300)),
                ('email', models.EmailField(max_length=300)),
                ('email_password', models.CharField(max_length=300)),
                ('bot_id', models.CharField(max_length=300)),
                ('bot_token', models.CharField(max_length=300)),
            ],
        ),
    ]
