# Generated by Django 2.1.5 on 2019-01-11 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announceusio', '0007_sitesettings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitesettings',
            old_name='bot_id',
            new_name='channel_id',
        ),
    ]
