# Generated by Django 2.1.5 on 2019-01-11 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announceusio', '0008_auto_20190111_1814'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitesettings',
            old_name='channel_id',
            new_name='discord_channel_id',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='discord_server_id',
            field=models.CharField(default='asds', max_length=300),
        ),
    ]
