# Generated by Django 2.1.5 on 2019-01-13 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announceusio', '0011_auto_20190111_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='message',
            field=models.TextField(default='{invite_url}'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='sub_days',
            field=models.IntegerField(default=30),
        ),
    ]
