# Generated by Django 2.1.5 on 2019-01-13 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announceusio', '0012_auto_20190113_1800'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitesettings',
            old_name='message',
            new_name='message_body',
        ),
    ]
