# Generated by Django 2.1.5 on 2019-01-13 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announceusio', '0013_auto_20190113_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='member_role',
            field=models.CharField(default='Member', max_length=255),
        ),
    ]
