# Generated by Django 2.1.5 on 2019-02-24 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('announceusio', '0017_sitesettings_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='auth.Group', unique=True),
        ),
    ]
