# Generated by Django 2.1.5 on 2019-03-06 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announceusio', '0018_botmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botmessage',
            name='help_message_body',
            field=models.TextField(default='```Supported commands:\n\n!activate example@example.com - you activate your membershp.\n\n!renew - you get membership renewal link.\n\n!status - gives days left before expiration.\n\n!help - show help message.\n```'),
        ),
    ]
