# Generated by Django 2.1.5 on 2019-03-09 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announceusio', '0021_auto_20190309_0455'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsettings',
            name='email_subject',
            field=models.CharField(default='Announceus.io Invite', max_length=255),
        ),
    ]
