# Generated by Django 2.1.5 on 2019-03-10 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announceusio', '0023_auto_20190310_0654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
    ]
