# Generated by Django 2.1.5 on 2019-03-10 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announceusio', '0024_auto_20190310_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='discord_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='discord_username',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
