# Generated by Django 2.1.5 on 2019-03-14 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announceusio', '0025_auto_20190310_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='stripe_token',
            field=models.CharField(default='', max_length=512),
        ),
    ]
