# Generated by Django 2.1.5 on 2019-03-16 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announceusio', '0026_billing_stripe_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stripe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(blank=True, max_length=64, null=True)),
                ('id_transaction', models.CharField(blank=True, max_length=16, null=True)),
                ('status', models.CharField(blank=True, max_length=16, null=True)),
                ('payer_email', models.EmailField(blank=True, max_length=300, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
