# Generated by Django 2.1.5 on 2019-03-17 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announceusio', '0028_billing_stripe_webhook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripe',
            name='id_transaction',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='stripe',
            name='payer_email',
            field=models.EmailField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='stripe',
            name='status',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
