# Generated by Django 2.1.5 on 2019-03-17 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announceusio', '0029_auto_20190317_0401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripe',
            name='id_transaction',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
