# Generated by Django 2.1.5 on 2019-03-17 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announceusio', '0030_auto_20190317_0420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripe',
            name='id_transaction',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
