# Generated by Django 2.1.5 on 2019-03-17 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announceusio', '0031_auto_20190317_0425'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='stripe_secret_token',
            field=models.CharField(default='', max_length=512),
        ),
    ]
