# Generated by Django 2.1.5 on 2019-05-05 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announceusio', '0033_stripe_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripe',
            name='customer',
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
    ]
